### ISSUE TITLE
YubiKey

### ISSUE THREAD

**Issue by cmac08** [pingidentity/pingid-powershell-scripts#1]
We're trying to automate a process for offline activations of YubiKey.
We're able to create the users using the script, but when I attempt to pair the YubiKey we receive the 200-Ok but it never completes the pairing process. 

Is there a step or process that needs to be completed in a certain order before I can pair a YubiKey?

**Comment by pm-ping** [comment]
I'm just investigating. Are you seeing the issue when you pair via the API, then attempt an SSO through PingOne? (ie when you attempt SSO you receive the PingID registration page instead of a YubiKey challenge)

**Comment by cmac08** [comment]
Correct, I am pairing via the API and attempting to SSO and receiving the PingID registration page.

**Comment by cmac08** [comment]
Any Update?

**Comment by pm-ping** [comment]
Can you try it again. This should have been resolved.

**Comment by cmac08** [comment]
I created a new user and attempted to pair the YubiKey. The user still has a status of Pending Activation even though the script returned a 200.

**Comment by pm-ping** [comment]
I have committed a fix for this issue. The Pair-YubiKey.ps1 was missing the line that executed the pair command.
