### ISSUE TITLE
Anyone able to Get-Org Report?

### ISSUE THREAD

**Issue by syannant** [pingidentity/pingid-powershell-scripts#11]
Have checked my API helper settings a million times but no matter what I get a 403 error code

My tenant is in the EU region, have tried using idpxnyl3m.pingidentity.eu instead but then I end up with a 400 error.

Anyone have any idea? Need to some get a automated report of users in PingID

```
VERBOSE: Calling PingID API:
VERBOSE: POST https://idpxnyl3m.pingidentity.com/pingid/rest/4/getorgreport/do with -1-byte payload
VERBOSE: FAILED - ERROR CODE: 
VERBOSE: 403
```

**Comment by asafd1** [comment]
Did you call CreateJob and GetJobStatus?
Do you manage to call other APIs successfully (like GetUser Details)? 
If it still doesn't work I suggest emailing support@pingidentity.com

**Comment by syannant** [comment]
So everything else seems to work. CreateJob, GetJobStatus, and GetUserDetails all work just fine.

After running CreateJob and GetJobStatus the error message is a little different but

```
PS C:\scripts\pingid-powershell-scripts-master\scripts> .\Get-Organization-Report.ps1 -FileType CSV -Verbose
VERBOSE: API Token:
VERBOSE: eyJhbGciOiJIUzI1NiIsInRva2VuIjoiNGQ1YzljN2Q3ZTM1NGMwYjgxOGViYmIyMjhiNmFmOGIiLCJvcmdBbGlhcyI6ImFjMjk3YWVlLTljNGYtNGIyYS1iNzA2LWJhYTkwMmQ3NmYxNCJ9.eyJyZXFIZWFkZXIiOnsic2VjcmV0S2V5IjoiNGQ1YzljN2Q3ZTM1NGMwYjgxOGViYmIyMjhiNmFmOGIiLCJ0aW1lc3RhbXAiOiIyMDE5LTA3LTE3IDEzOjE4OjI3WiIsInZlcnNpb24iOiI0LjkiLCJsb2NhbGU
iOiJlbiIsIm9yZ0FsaWFzIjoiYWMyOTdhZWUtOWM0Zi00YjJhLWI3MDYtYmFhOTAyZDc2ZjE0In0sInJlcUJvZHkiOnsiZmlsZVR5cGUiOiJDU1YifX0.cooQjiuyG8C4atV72k-INT2ZGkgn68W3MJOvFFAVK6U
VERBOSE: Calling PingID API:
VERBOSE: POST https://idpxnyl3m.pingidentity.eu/pingid/rest/4/getorgreport/do with -1-byte payload
VERBOSE: received 7008-byte response of content type application/octet-stream
VERBOSE: FAILED - ERROR CODE: 
Write-Verbose : Cannot bind argument to parameter 'Message' because it is null.
At C:\scripts\pingid-powershell-scripts-master\scripts\pingid-api-helper.ps1:160 char:17
+         Write-Verbose $_.Exception.Response.StatusCode.Value__
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Verbose], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteVerboseCommand
 
VERBOSE: FAILED
VERBOSE: Failed: Error code 

```

**Comment by syannant** [comment]
Success! Forgot to change the output path in the last run, the report downloaded successfully now.

Is this because I ran CreateJob earlier? Does this have to be run before Get-Org report?

I'm trying to automate this and have it run every couple of hours, and then pipe out the results to a different script that can add these users to a specific group in AD. So I am just trying to figure out the flow here.

Thanks!

**Comment by syannant** [comment]
Just to update if anyone else is having similar issues...
1. Run Create-Job
2. Wait a few seconds for job to complete I put in a 15 second pause
3. Run Get-Organization-Report

Thanks for the help

**Comment by asafd1** [comment]
There's no need to wait.
You should call GetJobStatus to know when the job is done.
