### ISSUE TITLE
pingid-api-helper.ps1 typographical error causing errors

### ISSUE THREAD

**Issue by gsmithx2** [pingidentity/pingid-powershell-scripts#4]
Note that there is a typo on line 153 of pingid-api-helper.ps1 where the wrong "dash" character is present in the -f option to compute the timestamp for downloading the report results when using the getorgreport endpoint.

**Comment by shaile8** [comment]
pull request - pingid-api-helper.ps1 typographical error causing errors - wrong "dash"
