### ISSUE TITLE
PingID Powershell script

### ISSUE THREAD

**Issue by srikend** [pingidentity/pingid-powershell-scripts#7]
is there a script to pull all the users  list in the PingiD ?

**Comment by asafd1** [comment]
yes: https://github.com/pingidentity/pingid-powershell-scripts/blob/master/Get-PingID-Report.ps1
it will pull all users and their devices per tenant

**Comment by srikend** [comment]
i tried running that script but i get Null error.
PS C:\pingid\scripts> .\Get-PingID-Report.ps1

cmdlet Get-PingID-Report.ps1 at command pipeline position 1
Supply values for the following parameters:
FileType: CSV

cmdlet Create-Job.ps1 at command pipeline position 1
Supply values for the following parameters:
JobType: USER_REPORTS
*******************************************
Job Completed!
Write-Verbose : Cannot bind argument to parameter 'Message' because it is null.
At C:\pingid\scripts\pingid-api-helper.ps1:160 char:17
+         Write-Verbose $_.Exception.Response.StatusCode.Value__
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Verbose], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteVerbos
   eCommand

**Comment by srikend** [comment]
can you help me with what i am missing here ?

**Comment by dorheini** [comment]
Hi @srikend. 
We will check this on our side in the next few days. I’ll keep you posted. 

Thanks

**Comment by srikend** [comment]
Thanks, i was able to figure it out.
